# chat_utils.py

import streamlit as st

def append_user_message(user_input):
    """
    Appends the user's message to the chat history stored in session state.
    
    Parameters:
    - user_message: The message entered by the user (string).
    """

    st.session_state.messages.append({"role": "user", "content": user_input})
    with st.chat_message("user"):
        st.markdown(user_input)

def append_assistant_message(assistant_response):
    """
    Appends the assistant's message to the chat history stored in session state.
    
    Parameters:
    - assistant_message: The message generated by the assistant (string).
    """

    st.session_state.messages.append({"role": "assistant", "content": assistant_response})

def display_chat_messages():
    """
    Displays the chat history by iterating through the messages stored in session state.
    Each message is displayed in a distinct format based on the role (user/assistant).
    """

    for message in st.session_state.messages:
        if message["role"] == "user":
            with st.chat_message("user"):
                st.markdown(message["content"])
        elif message["role"] == "assistant":
            with st.chat_message("assistant"):
                st.markdown(message["content"])